# Generated by Django 2.1.3 on 2018-11-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='card_name')),
                ('classification', models.IntegerField(choices=[(1, 'モンスター'), (2, '魔法'), (3, '罠')], verbose_name='classification')),
                ('card_effect', models.TextField(verbose_name='card_effect')),
            ],
        ),
    ]
