# Generated by Django 2.1.3 on 2018-11-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_cardDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='phonetic',
            field=models.CharField(default='', max_length=65535, verbose_name='phonetic'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=65535, primary_key=True, serialize=False, verbose_name='card_name'),
        ),
    ]
